version: '3.1'

services:
  docservice:
    build: .
    image: docservice
    environment:
      - DBUSER=root
      - DBPASS=password
      - DBHOST=mongo
    depends_on:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - docstorage:/document_storage
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
volumes:
  docstorage:
